# --- Main Colors ---
background            #1a120e
foreground            #f0dfd8
cursor                #f0dfd8
cursor_text_color     #1a120e

selection_background  #5c4033
selection_foreground  #ffdbcb

url_color             #cfc890

# --- ANSI Colors ---
color0                #1a120e
color1                #ffb4ab
color2                #cfc890
color3                #e6beac
color4                #ffb691
color5                #cfc890
color6                #e6beac
color7                #f0dfd8

color8                #52443d
color9                #93000a
color10               #4c481c
color11               #5c4033
color12               #703716
color13               #5c4033
color14               #4c481c
color15               #d7c2b9

# --- Starship Prompt Bubbles ---
color255              #703716
color254              #ffb691
color253              #5c4033
color252              #e6beac
color251              #4c481c
color250              #cfc890
color249              #93000a
color248              #ffb4ab

color232              #ffdbcb
color233              #542103
color234              #ffdbcb
color235              #432a1e
color236              #ece4aa
color237              #353107
color238              #ffdad6
color239              #690005
color240              #ffdbcb

# Matched with unthemed light/dark
color243              #ffb691
color244              #ffb4ab
color245              #52443d

# --- UI Elements ---
active_tab_foreground   #542103
active_tab_background   #ffb691
inactive_tab_foreground #ffdbcb
inactive_tab_background #703716

active_border_color     #ffb691
inactive_border_color   #a08d85

# --- Marks ---
mark1_foreground        #341100
mark1_background        #ffdbcb
mark2_foreground        #2c160b
mark2_background        #ffdbcb
mark3_foreground        #1f1c00
mark3_background        #ece4aa
