[config]

[templates.hyprland]
input_path = './templates/hyprland-colors.lua'
output_path = '~/.config/hypr/modules/colors.lua'

[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = './templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.discord]
input_path = './templates/discord.css'
output_path = '~/.config/vesktop/themes/seam.theme.css'

[templates.neovim]
input_path = './templates/neovim.lua'
output_path = '~/.config/nvim/lua/plugins/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.m3colors]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'
